name: floating_log_app
description: Flutter Windows 悬浮日志 MVP 示例
version: 0.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  window_manager: ^0.3.2
  bitsdojo_window: ^0.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  file_picker: ^10.3.8
  flex_color_picker: ^3.8.0
  desktop_multi_window: ^0.3.0   # ⭐ 新增

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
